// Generated by ego.
// DO NOT EDIT

//line breadcrumb.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type Breadcrumb struct {
	Yield func()
}

func (c *Breadcrumb) Render(ctx context.Context, w io.Writer) {
//line breadcrumb.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
