// Generated by ego.
// DO NOT EDIT

//line card_deck.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type CardDeck struct {
	Yield func()
}

func (c *CardDeck) Render(ctx context.Context, w io.Writer) {
//line card_deck.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
