// Generated by ego.
// DO NOT EDIT

//line card_columns.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type CardColumns struct {
	Yield func()
}

func (c *CardColumns) Render(ctx context.Context, w io.Writer) {
//line card_columns.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
