// Generated by ego.
// DO NOT EDIT

//line dropdown.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type Dropdown struct {
	Yield func()
}

func (c *Dropdown) Render(ctx context.Context, w io.Writer) {
//line dropdown.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
