// Generated by ego.
// DO NOT EDIT

//line dropdown_header.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type DropdownHeader struct {
	Yield func()
}

func (c *DropdownHeader) Render(ctx context.Context, w io.Writer) {
//line dropdown_header.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
