// Generated by ego.
// DO NOT EDIT

//line dropdown_menu.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type DropdownMenu struct {
	Yield func()
}

func (c *DropdownMenu) Render(ctx context.Context, w io.Writer) {
//line dropdown_menu.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
