// Generated by ego.
// DO NOT EDIT

//line form_control.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type FormControl struct {
	Yield func()
}

func (c *FormControl) Render(ctx context.Context, w io.Writer) {
//line form_control.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
