// Generated by ego.
// DO NOT EDIT

//line input_group.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type InputGroup struct {
	Yield func()
}

func (c *InputGroup) Render(ctx context.Context, w io.Writer) {
//line input_group.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
