// Generated by ego.
// DO NOT EDIT

//line jumbotron.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type Jumbotron struct {
	Yield func()
}

func (c *Jumbotron) Render(ctx context.Context, w io.Writer) {
//line jumbotron.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
