// Generated by ego.
// DO NOT EDIT

//line list_group.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type ListGroup struct {
	Yield func()
}

func (c *ListGroup) Render(ctx context.Context, w io.Writer) {
//line list_group.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
