// Generated by ego.
// DO NOT EDIT

//line list_group_item.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type ListGroupItem struct {
	Yield func()
}

func (c *ListGroupItem) Render(ctx context.Context, w io.Writer) {
//line list_group_item.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
