// Generated by ego.
// DO NOT EDIT

//line popover.ego:1
package bootstrap

import "fmt"
import "html"
import "io"
import "context"

type Popover struct {
	Yield func()
}

func (c *Popover) Render(ctx context.Context, w io.Writer) {
//line popover.ego:10
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
