// Generated by ego.
// DO NOT EDIT

//line main.ego:1
package main

import "fmt"
import "html"
import "io"
import "context"

import "github.com/benbjohnson/bootstrap-ego"

func RenderAlert(ctx context.Context, w io.Writer) {
//line main.ego:7
	{
		egoComponent := bootstrap.Alert{
			Yield: func() {
//line main.ego:7
				_, _ = io.WriteString(w, "Hello")
			},
		}
		egoComponent.Render(ctx, w)
	}
//line main.ego:8
}

func RenderBadge(ctx context.Context, w io.Writer) {
//line main.ego:11
	{
		egoComponent := bootstrap.Badge{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:12
}

func RenderBreadcrumb(ctx context.Context, w io.Writer) {
//line main.ego:15
	{
		egoComponent := bootstrap.Breadcrumb{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:16
}

func RenderButton(ctx context.Context, w io.Writer) {
//line main.ego:19
	{
		egoComponent := bootstrap.Button{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:20
}

func RenderButtonGroup(ctx context.Context, w io.Writer) {
//line main.ego:23
	{
		egoComponent := bootstrap.ButtonGroup{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:24
}

func RenderCard(ctx context.Context, w io.Writer) {
//line main.ego:27
	{
		egoComponent := bootstrap.Card{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:28
}

func RenderCardColumns(ctx context.Context, w io.Writer) {
//line main.ego:31
	{
		egoComponent := bootstrap.CardColumns{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:32
}

func RenderCardDeck(ctx context.Context, w io.Writer) {
//line main.ego:35
	{
		egoComponent := bootstrap.CardDeck{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:36
}

func RenderCarousel(ctx context.Context, w io.Writer) {
//line main.ego:39
	{
		egoComponent := bootstrap.Carousel{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:40
}

func RenderCollapse(ctx context.Context, w io.Writer) {
//line main.ego:43
	{
		egoComponent := bootstrap.Collapse{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:44
}

func RenderDropdown(ctx context.Context, w io.Writer) {
//line main.ego:47
	{
		egoComponent := bootstrap.Dropdown{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:48
}

func RenderDropdownHeader(ctx context.Context, w io.Writer) {
//line main.ego:51
	{
		egoComponent := bootstrap.DropdownHeader{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:52
}

func RenderDropdownItem(ctx context.Context, w io.Writer) {
//line main.ego:55
	{
		egoComponent := bootstrap.DropdownItem{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:56
}

func RenderDropdownMenu(ctx context.Context, w io.Writer) {
//line main.ego:59
	{
		egoComponent := bootstrap.DropdownMenu{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:60
}

func RenderForm(ctx context.Context, w io.Writer) {
//line main.ego:63
	{
		egoComponent := bootstrap.Form{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:64
}

func RenderFormCheck(ctx context.Context, w io.Writer) {
//line main.ego:67
	{
		egoComponent := bootstrap.FormCheck{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:68
}

func RenderFormCheckInput(ctx context.Context, w io.Writer) {
//line main.ego:71
	{
		egoComponent := bootstrap.FormCheckInput{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:72
}

func RenderFormControl(ctx context.Context, w io.Writer) {
//line main.ego:75
	{
		egoComponent := bootstrap.FormControl{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:76
}

func RenderFormControlFile(ctx context.Context, w io.Writer) {
//line main.ego:79
	{
		egoComponent := bootstrap.FormControlFile{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:80
}

func RenderFormGroup(ctx context.Context, w io.Writer) {
//line main.ego:83
	{
		egoComponent := bootstrap.FormGroup{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:84
}

func RenderFormRow(ctx context.Context, w io.Writer) {
//line main.ego:87
	{
		egoComponent := bootstrap.FormRow{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:88
}

func RenderFormText(ctx context.Context, w io.Writer) {
//line main.ego:91
	{
		egoComponent := bootstrap.FormText{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:92
}

func RenderInputGroup(ctx context.Context, w io.Writer) {
//line main.ego:95
	{
		egoComponent := bootstrap.InputGroup{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:96
}

func RenderJumbotron(ctx context.Context, w io.Writer) {
//line main.ego:99
	{
		egoComponent := bootstrap.Jumbotron{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:100
}

func RenderListGroup(ctx context.Context, w io.Writer) {
//line main.ego:103
	{
		egoComponent := bootstrap.ListGroup{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:104
}

func RenderListGroupItem(ctx context.Context, w io.Writer) {
//line main.ego:107
	{
		egoComponent := bootstrap.ListGroupItem{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:108
}

func RenderModal(ctx context.Context, w io.Writer) {
//line main.ego:111
	{
		egoComponent := bootstrap.Modal{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:112
}

func RenderNav(ctx context.Context, w io.Writer) {
//line main.ego:115
	{
		egoComponent := bootstrap.Nav{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:116
}

func RenderNavbar(ctx context.Context, w io.Writer) {
//line main.ego:119
	{
		egoComponent := bootstrap.Navbar{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:120
}

func RenderPagination(ctx context.Context, w io.Writer) {
//line main.ego:123
	{
		egoComponent := bootstrap.Pagination{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:124
}

func RenderPills(ctx context.Context, w io.Writer) {
//line main.ego:127
	{
		egoComponent := bootstrap.Pills{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:128
}

func RenderPopover(ctx context.Context, w io.Writer) {
//line main.ego:131
	{
		egoComponent := bootstrap.Popover{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:132
}

func RenderProgress(ctx context.Context, w io.Writer) {
//line main.ego:135
	{
		egoComponent := bootstrap.Progress{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:136
}

func RenderTabs(ctx context.Context, w io.Writer) {
//line main.ego:139
	{
		egoComponent := bootstrap.Tabs{}
		egoComponent.Render(ctx, w)
	}
//line main.ego:140
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
