// Generated by ego.
// DO NOT EDIT

//line main.ego:1
package main

import "fmt"
import "html"
import "io"
import "context"

import "github.com/benbjohnson/bootstrap-ego"

func Head(ctx context.Context, w io.Writer) {
//line main.ego:7
	_, _ = io.WriteString(w, "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css\" integrity=\"sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy\" crossorigin=\"anonymous\">\n\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js\" integrity=\"sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4\" crossorigin=\"anonymous\"></script>\n")
//line main.ego:11
}

func AlertRenderer(style string) func(ctx context.Context, w io.Writer) {
	return func(ctx context.Context, w io.Writer) {

//line main.ego:15
		{
			egoComponent := bootstrap.Alert{
				Style: style,
				Yield: func() {
//line main.ego:15
					_, _ = io.WriteString(w, "This is a ")
//line main.ego:15
					_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(style)))
//line main.ego:15
					_, _ = io.WriteString(w, " alert.")
				},
			}
			egoComponent.Render(ctx, w)
		}
//line main.ego:15
	}
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
